### ISSUE TITLE
amd epp not working

### ISSUE THREAD

**Issue by jothi-prasath** [CachyOS/linux-cachyos#48] opened 2022-11-22 16:51 UTC
i installed linux-cachyos linux-cachyos-rc linux-bore   but none of them have amd-pstate or amd-epp

**Comment by sirlucjan** [comment] 2022-11-22 16:53
@ptr1337 uses amd-pstate so will certainly be able to advise you.

**Comment by ptr1337** [comment] 2022-11-22 16:55
Hey!

The cmdline has been changed in the latest patch of amd-pstate-epp v4.
I made here a little info how to use it:
https://wiki.cachyos.org/en/home/General_System_Tweaks

Check if your CPU provides the CPPC MSR with `lscpu | grep cppc.` Mainly newer ZEN APU's or ZEN4 Desktop CPUs should provide it

If your CPU does provide the MSR add to your boot cmdline following:

    AMD PSTATE: `amd-pstate=passive`
    AMD PSTATE EPP:` amd-pstate=active`

If your CPU does not provide the cppc, you need to use the legacy_cppc solution:

    AMD PSTATE: `amd-pstate=passiv amd_pstate=legacy_cppc`
    AMD PSTATE EPP: `amd-pstate=active amd_pstate=legacy_cppc`

**Comment by jothi-prasath** [comment] 2022-11-22 17:06
it works, thanks @ptr1337 @sirlucjan

**Comment by xuanruiqi** [comment] 2022-11-29 11:31
Hey, not exactly same question, but after I enable AMD PState, my CPU is locked to the lowest frequency after every suspend. Any idea why, or is it just a bug?

My CPU is an AMD Ryzen 5 3600, and my motherboard is ASUS Gaming X570-PLUS.

**Comment by ptr1337** [comment] 2022-11-29 11:37
suspend to idle seems generally a bit buggy with the current 6.0 Kernel and the latest systemd version.
Is this issue just happening when you suspend?

Otherwise I would say reporting a bug to the creator of the amd-pstate-epp patch would be the best idea, if this is just happening with the amd-pstate-epp or also amd-pstate or acpi-cpufreq?

**Comment by xuanruiqi** [comment] 2022-11-29 12:06
Only pstate (both epp and non-epp). acpi-cpufreq seems bug free. This is definitely a regression as no such bug was observed when I was using the older version of amd-pstate-epp! Will report a bug to amd-pstate-epp maintainers.

**Comment by ptr1337** [comment] 2022-11-29 13:26
> Only pstate (both epp and non-epp). acpi-cpufreq seems bug free. This is definitely a regression as no such bug was observed when I was using the older version of amd-pstate-epp! Will report a bug to amd-pstate-epp maintainers.

Ill update later linux-cachyos-rc into the repo. It has the latest v5 patchset in, maybe it does fix it?

**Comment by xuanruiqi** [comment] 2022-11-29 15:46
Thank you. I'll try when you commit.

**Comment by jothi-prasath** [comment] 2022-11-30 08:33
> Thank you. I'll try when you commit.

me too

**Comment by jothi-prasath** [comment] 2022-11-30 08:33
oops

**Comment by ptr1337** [comment] 2022-11-30 09:23
I have updated the patchset (https://github.com/CachyOS/kernel-patches/commit/9bb8b7bd653db0800975a8386aa1774a1cdb7c5f) for 6.1 and compiled linux-cachyos-rc into the cachyos repo.

**Comment by xuanruiqi** [comment] 2022-11-30 17:35
Unfortunately the problem persists. I did email the maintainers at AMD (Perry and Ray) and they say they're working on it.

**Comment by ptr1337** [comment] 2022-12-01 09:59
> Unfortunately the problem persists. I did email the maintainers at AMD (Perry and Ray) and they say they're working on it.

Good to know that it is a upstream issue, thanks for reporting it to the maintainers! :)

**Comment by fbernier** [comment] 2022-12-21 17:56
FYI a [new version of the patchet](https://lore.kernel.org/lkml/20221219064042.661122-1-perry.yuan@amd.com/T/#t) was posted two days ago.

**Comment by ptr1337** [comment] 2022-12-21 17:59
I have already updated and use it.
https://github.com/CachyOS/linux/commit/753eda2bab09c25a0e44ce3cb0cada5d6e708f73

The patchset will get updated with the 6.1.1 patch, which just got released :)

**Comment by ptr1337** [comment] 2022-12-21 19:38
Patches got updated:
https://github.com/CachyOS/kernel-patches/commit/b82a76ca3b4d919b07f5c4f5baff24de37d611be

Be aware if compiling with modprobed-db, that currently amd-pstate depends on the INTEL_PSTATE variable, which is currently not set at the patch itself and will be fixed with the v9 version.

Kernel got also updated to 6.1.1:
https://github.com/CachyOS/linux-cachyos/commit/a9720e168d0b41c365afeb650cf9fb3ab82e0327

**Comment by fbernier** [comment] 2022-12-21 20:04
> Be aware if compiling with modprobed-db, that currently amd-pstate depends on the INTEL_PSTATE variable, which is currently not set at the patch itself and will be fixed with the v9 version.

Is there any possible workaround meanwhile, or the only way is to not compile with modprobed-db ?

**Comment by ptr1337** [comment] 2022-12-21 22:02
> > Be aware if compiling with modprobed-db, that currently amd-pstate depends on the INTEL_PSTATE variable, which is currently not set at the patch itself and will be fixed with the v9 version.
> 
> Is there any possible workaround meanwhile, or the only way is to not compile with modprobed-db ?

I just tested with my modprobed-db machine, if it works. It appears to be enabled. So it should be fine.

**Comment by alexjp** [comment] 2022-12-22 15:54
thanks @ptr1337 for the awesome kernels, I have been using bore-lto for a while now and working very well. :)

this latest amd pstate epp patchset now doesn't "enable my ryzen 3700x turbo cores" ( meaning, max it goes is 3.60 Ghz, instead of 4.40Ghz )

back to amd-pstate and custom ondemand profile

**Comment by alexjp** [comment] 2022-12-22 16:13
> Have you enabled the dynamic boost via the sysfs before ? As default it is setting it to 0.

actually no, never needed to :) now on ondemand, and works without needing to enable it :)

> Did you tried to set a different preference or change to the performance/powersave gov?

I did try, but didn't work...always said "binary file empty" when trying to enable performance. power didn't work too.
( i did check the source patches. he there mentions some examples, but didn't work for me )

I will wait to see if this only happens on this patchset, if it continues i will email him.

(I will check other things later, right now I can't reboot into active pstate epp mode)

**Comment by ptr1337** [comment] 2022-12-25 17:44
@alexjp 

I wrote something how to use the amd-pstate-epp driver. 
https://wiki.cachyos.org/en/home/General_System_Tweaks

The v9 series just got released. It will land into linux-cachyos 6.1.2 as soon it is released. 
Diff to v8:
https://github.com/CachyOS/linux/compare/a2865924f30f...aaa3a47738fd

changes from v8:
 * drive all the feedbacks from Mario and change the codes in this
  version
 * drive all the feedbacks from Ray and change the codes in this
  version
 * pick up all the R-B flags from Mario
 * pick up all the R-B flags from Ray
 * drop boost/refresh_freq_limits callback
 * reuse policy->driver_data to store amd_cpudata struct
 * use switch-case in the driver mode switching function
 * add Kconfig dependency the INTEL_PSTATE for AMD_PSTATE build
 * fix some other code format and typos


I hope it will fix your current issue, alex :)

**Comment by ptr1337** [comment] 2022-12-31 14:05
It took a bit time that 6.1.2 got released.

Here are the changes from the old patchset:
https://github.com/CachyOS/kernel-patches/commit/dec494c79b0106fcf9868a345358d0ed46a064df

amd-pstate-v9 is included and I hope it fixes the issues

**Comment by xuanruiqi** [comment] 2023-01-01 07:11
I think it is fixed.
But the AUR package needs a pkgrel bump. Sometimes there are quite long gaps between AUR pkgrel bumps and patch updates; maybe it would be a good idea to instead hard-code the commit hash into the PKGBUILD to prevent these problems.

**Comment by ptr1337** [comment] 2023-01-01 14:00
> I think it is fixed. But the AUR package needs a pkgrel & hash bump. Sometimes there are quite long gaps between AUR pkgrel bumps and patch updates; maybe it would be a good idea to instead hard-code the commit hash into the PKGBUILD to prevent these problems.

Hi!
Good that it is solved. I waited because I found a issue in the rtw88 patch which was needed to fix. I have updated the AUR.

**Comment by alexjp** [comment] 2023-01-02 04:51
@ptr1337 sorry for so late!

the new kernel update ( I am using bore-lto, i am not really up to date to what many editions do or why, just kept using that ) is working again properly with amd pstate epp !

thanks for the 6.1.2 update!

**Comment by sirlucjan** [comment] 2023-01-03 14:56
@alexjp If you think the problem is solved then I would ask you to close the thread.

**Closed** 2023-01-16 07:39 UTC

**Comment by ptr1337** [comment] 2023-01-20 15:49
amd-pstate-epp got updated once again.
The v11 will be in 6.1.8 and 6.2.0rc4.

Also we will add the amd-pstate guided patchset as an alternative to the active(epp) and passive (default amd-pstate)
